apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudsync
  namespace: contoso-supermarket
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: cloudsync
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: ./agora/pos_cloud_sync/operations/charts
  values:
    acr_name: agacr67266
    branch_name: "production"
    image_tag: v1.0
    github_User: sebassem
    queue_monitoring:
      timezone: "Pacific Standard Time"
    postgres:
      username: "postgres"
      database: "contoso"
    cosmos:
      container: "Orders"
      database: "Orders"
      endpoint: https://agcosmos67266.documents.azure.com:443/